version: 2
updates:
  # Atualizações de dependências npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "n8n-brasil"
    assignees:
      - "n8n-brasil"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
      - "automated"
    # Configurações específicas para segurança
    ignore:
      # Ignorar dependências que precisam de atualização manual
      - dependency-name: "@docusaurus/*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
    # Priorizar atualizações de segurança
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Verificar vulnerabilidades conhecidas
    vulnerability-alerts: true

  # Atualizações de GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "n8n-brasil"
    assignees:
      - "n8n-brasil"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated" 