name: Validate Documentation Overlaps

on:
  pull_request:
    branches: [ main, master ]
    paths:
      - 'docs/**'
      - 'sidebars.json'
      - 'scripts/validate-overlaps.js'
  push:
    branches: [ main, master ]
    paths:
      - 'docs/**'
      - 'sidebars.json'
      - 'scripts/validate-overlaps.js'

jobs:
  validate-overlaps:
    name: Validate Documentation Structure and Content
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run overlap validation
        run: npm run validate-overlaps
        
      - name: Upload validation report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: overlap-validation-report
          path: overlap-report.json
          retention-days: 30
          
      - name: Comment PR with results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            
            try {
              const report = JSON.parse(fs.readFileSync('overlap-report.json', 'utf8'));
              
              let comment = `## 📋 Relatório de Validação de Overlaps\n\n`;
              comment += `**Status:** ${report.metadata.totalIssues === 0 ? '✅ Passou' : '⚠️ Problemas encontrados'}\n\n`;
              comment += `**Resumo:**\n`;
              comment += `- Problemas de estrutura: ${report.summary.structure}\n`;
              comment += `- Palavras-chave suspeitas: ${report.summary.keyword}\n`;
              comment += `- Conteúdo duplicado: ${report.summary.content}\n`;
              comment += `- Conteúdo similar: ${report.summary.similarity}\n\n`;
              
              if (report.recommendations.length > 0) {
                comment += `**💡 Recomendações:**\n`;
                report.recommendations.forEach(rec => {
                  comment += `- ${rec.message} (${rec.count} itens)\n`;
                });
                comment += `\n`;
              }
              
              if (report.issues.length > 0) {
                comment += `**🔍 Problemas Detalhados:**\n`;
                report.issues.slice(0, 10).forEach(issue => {
                  comment += `- **${issue.type.toUpperCase()}**: ${issue.message}\n`;
                  comment += `  - Arquivo: \`${issue.path}\`\n`;
                });
                
                if (report.issues.length > 10) {
                  comment += `\n*... e mais ${report.issues.length - 10} problemas. Verifique o relatório completo.*\n`;
                }
              }
              
              comment += `\n📄 [Relatório completo disponível nos artifacts](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})\n`;
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
              
            } catch (error) {
              console.error('Erro ao processar relatório:', error);
              
              const errorComment = `## ❌ Erro na Validação de Overlaps\n\n`;
              errorComment += `Ocorreu um erro durante a validação. Verifique:\n`;
              errorComment += `- Se o arquivo \`sidebars.json\` está válido\n`;
              errorComment += `- Se todas as dependências estão instaladas\n`;
              errorComment += `- Os logs de execução para mais detalhes\n`;
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: errorComment
              });
            }
            
      - name: Fail on validation errors
        if: failure()
        run: |
          echo "❌ Validação de overlaps falhou!"
          echo "Verifique o relatório para detalhes sobre os problemas encontrados."
          echo "Consulte o CONTRIBUTING.md para guidelines sobre como evitar overlaps."
          exit 1 